@startuml

skinparam tabSize 2
' avoid problems with angled crows feet
skinparam linetype ortho

title "Kelp/Eigen Logical Entities"

entity "Staker" as staker <<Account>> {
}

entity "Deposit\nPool" as dep <<Kelp>> {
}

entity "Node\nDelegator" as del <<Kelp>> {
}

entity "Operator" as op <<Eigen>> {
}

entity "Strategy" as strat <<Eigen>> {
}

entity "Asset" as asset <<Token>> {
}

entity "Pod" as pod <<Eigen>> {
}

entity "Terms of\nService" as terms <<Eigen>> {
}

staker }o..o| dep

dep ||.o{ del

del }o..|| op

op }o.o| terms
' terms |o.o{ op

del ||...|| pod

del }o...o{ strat

' strat }o.|| asset÷
asset ||.o{ strat
dep |o...o{ asset

@enduml

'  Zero or One	|o--
' Exactly One	||--
' Zero or Many	}o--
' One or Many	}|--