@startuml

skinparam tabSize 2
' avoid problems with angled crows feet
skinparam linetype ortho

title "Native Restaking Logical Entities"

entity "Staker" as staker <<Account>> {
}

entity "Deposit\nPool" as dep <<Prime>> {
}

entity "primeETH" as lp <<Prime>> {
}

entity "Node\nDelegator" as del <<Prime>> {
}

' entity "Operator" as op <<P2P>> {
' }

entity "Pod\nManager" as podMan <<EigenLayer>> {
}

entity "Pod" as pod <<EigenLayer>> {
}

' entity "Slasher" as slash <<EigenLayer>> {
' }

entity "Validator" as val {
}

entity "Deposit" as bdep <<Beacon>> {
}
entity "Delayed\nWithdraw\nRouter" as withdraw <<EigenLayer>> {
}

entity "Cluster" as cluster <<SSV>> {
}

entity "Operator" as ssvOp <<SSV>> {
}

staker }o..o| dep

dep ||.|| lp
dep ||..|{ del

del }o..|| podMan
podMan ||..o{ pod
' podMan ||.|| withdraw
withdraw ||.|| podMan
' slash ||.|| podMan

del ||...o| pod

pod |o..o{ val

pod }o....|| bdep
' withdraw ||..o{ pod

del |o....o| cluster
cluster }o..{ ssvOp
cluster |o..o{ val
' ssvOp |o.|o{val
val }o.{ ssvOp

@enduml

'  Zero or One	|o--
' Exactly One	||--
' Zero or Many	}o--
' One or Many	}|--